Get macOS/*nix autodetect_compiler working

diff --git a/runtime/unix/within-dev b/runtime/unix/within-dev
--- a/runtime/unix/within-dev
+++ b/runtime/unix/within-dev
@@ -155,10 +155,10 @@ if [ "$COMPILATION" = ON ]; then
     else
         autodetect_compiler "$LAUNCHER"
     fi
-    EXITCODE=$? # 1 is not a Windows machine but is OK
+    EXITCODE=$?
     set -e
-    if [ $EXITCODE -eq 2 ]; then
-        echo "FATAL: Did not detect a completed Diskuv OCaml installation"
+    if [ $EXITCODE -ne 0 ]; then
+        echo "FATAL: Your system is missing a compiler, which should be installed if you have completed the Diskuv OCaml installation"
         exit 1
     fi
 fi
