Provide better naming/errors for vagrant up

diff --git a/.github/workflows/vagrant-win32.yml b/.github/workflows/vagrant-win32.yml
--- a/.github/workflows/vagrant-win32.yml
+++ b/.github/workflows/vagrant-win32.yml
@@ -24,8 +24,13 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-vagrant-
 
-    - name: Run vagrant up
+    - name: '"vagrant up" for release "${{ github.ref_name }}"'
+      if: ${{ github.ref_type == 'tag' }}
       run: cd vagrant/win32 && vagrant up
+
+    - name: '"vagrant up" for **previous** release'
+      if: ${{ github.ref_type != 'tag' }}
+      run: 'cat .dkmlroot && cd vagrant/win32 && if ! vagrant up; printf "FATAL: Vagrant failed to start up for\n"; sed "s/^/  /" .dkmlroot; fi'
 
     - name: Check test_installation.t status
       run: |
